
graphql:
  image: gcr.io/jamplay-deploy-poc/jamplay-comment:latest
  links:
    - mongo:mongo
  volumes:
    - ./.env:/usr/app/.env
  ports:
    - 1671:1671

mongo:
  image: mongo:3.4
  volumes_from:
    - mongo-data
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null --setParameter failIndexKeyTooLong=false"

mongo-data:
  image: mongo:3.4
  volumes:
    - ./.db/:/data/db
  command: "--break-mongo" # break mongod command and use it as data-volume-container